package pl.edu.agh.northwind.NorthwindApp.entities;

// Generated 2014-10-13 21:10:57 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Shippers generated by hbm2java
 */
@Entity
@Table(name = "shippers", catalog = "northwindDB")
public class Shippers implements java.io.Serializable {

	private Integer shipperId;
	private String companyName;
	private String phone;

	public Shippers() {
	}

	public Shippers(String companyName, String phone) {
		this.companyName = companyName;
		this.phone = phone;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ShipperID", unique = true, nullable = false)
	public Integer getShipperId() {
		return this.shipperId;
	}

	public void setShipperId(Integer shipperId) {
		this.shipperId = shipperId;
	}

	@Column(name = "CompanyName", length = 40)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "Phone", length = 24)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
